"""added created_at and updated_at

Revision ID: dc7dd6e2cfb9
Revises:
Create Date: 2025-03-16 11:19:59.822540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7dd6e2cfb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('coupons', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'updated_at')
    op.drop_column('coupons', 'created_at')
    # ### end Alembic commands ###
